### ISSUE TITLE
evaluate "planetiler"

### ISSUE THREAD

**Issue by MichaelKreil** [versatiles-org/versatiles-generator#4]
Is planetiler an alternative to our current vector tile generation process?

**Comment by koufopoulosf** [comment]
Hi @MichaelKreil, I think the basemap that you have is quite complete. For example,

https://tiles.versatiles.org/#14.76/39.35154/22.94288

Meaning, this one here:

![image](https://github.com/versatiles-org/versatiles-generator/assets/66564413/889af42f-8562-4f5c-b032-7b0f42ac1f31)

I haven't found it on any other vector tile (base)map.

How do you generate these tiles? Also, I have made an issue here as well:

https://github.com/versatiles-org/versatiles-rs/issues/27

Is that fixable?


Thanks in advance for your valuable time!
